# Generated by Django 4.1.7 on 2023-10-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_comment_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_listing', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
