# Generated by Django 4.1.7 on 2023-10-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_bid_bid_bidder_bid_listing_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
