# Generated by Django 4.1.7 on 2023-10-25 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='list_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='list_item',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_item_watchlist', to='auctions.listing'),
        ),
    ]
